<script setup></script>

<template>
  <div class="artworks">
    <h3>Nichts als Solide (Nothing but Solid)</h3>
    <p class="fichatecnica">Video, 2021</p>
    <p>
      The room installation "Nichts als Solide" can be understood as an
      examination of those traces that people leave in their surroundings and
      that are burned into landscapes and places. In conversation with poems by
      the Jewish poet Mascha Kaléko and the Afro-German poet May Ayim, which
      serve as a data set for an artificial intelligence, a monologue emerges in
      which a new, fictional lyric self is formed. Through the medium of this
      virtual being, the artist not only asks questions about identity, but also
      answers them with self-empowerment by constructing a text with the
      statements generated by the AI and her own words in a context that gives
      rise to a decided stance.
    </p>
    <br />
    <h4>
      <a
        href="https://www.vanessaopoku.com/"
        target="_blank"
        rel="noopener noreferrer"
        >Vanessa A. Opoku</a
      >
    </h4>
    <p>
      Vanessa A. Opoku (*1992) is a visual artist living and working in Berlin.
      She studied at the Academy of Fine Arts Vienna, Bezalel Academy of Art and
      Design Jerusalem and graduated in 2021 in the field of artistic
      photography at the Academy of Fine Arts in Leipzig with a Diploma in Fine
      Arts. She is currently pursuing her post-grad with Tina Bara at the HGB
      Leipzig. She has been a scholarship holder of the
      Rosa-Luxemburg-Foundation since 2014 and in 2022 she won the gute
      aussichten Prize for Young German Photography. In her artistic practice,
      digital media, photogrammetry and AI form the starting point with which
      she negotiates the boundaries of mixed reality and finds alliances between
      art, science and technology.
    </p>
  </div>
</template>
